- hosts: all
  become: true
  pre_tasks:

  - name: Update Ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Configure dpkg for Ubuntu
    shell:
      dpkg --configure -a
    when: ansible_distribution == "Ubuntu"

  - name: Install pip for Python 3
    apt:
      name: python3-pip
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Install Docker (Ubuntu)
    apt:
      name: docker
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install Docker Python SDK
    pip:
      name: docker-py
      executable: pip3
    when: ansible_distribution == "Ubuntu"

  - name: Add user to Docker group
    shell:
      usermod -aG docker srhmshan

  - name: Enable and restart Docker service on Ubuntu
    service:
      name: docker
      state: started
      enabled: true

  - name: Create directory for Dockerfile
    file:
      path:  ./root/demo-dockerfile
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: Copy Dockerfile to the directory
    copy:
      src:  ./Dockerfile
      dest: ./root/demo-dockerfile/Dockerfile
      owner: root
      group: root
      mode: '0755'

  - name: Build Docker image from Dockerfile
    docker_image:
      name: hoa11
      build:
        path: ./root/demo-dockerfile
        args:
          listen_port: 8080
      state: present

  - name: Run Docker container and expose port
    shell:
      docker run -it -d -p 8080:80 hoa11
